- name: configure interface lo
  copy:
    src: lo
    dest: /etc/network/interfaces.d/lo


- name: configure interface ens33
  template:
    src: ens33
    dest: /etc/network/interfaces.d/ens33


- name: set /etc/network/interfaces
  copy:
    src: interfaces
    dest: /etc/network/interfaces
    backup: yes

